name: Copy Repo to S3

on:
  push:
    branches:
      - main

jobs:
  copy_to_s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Copy repo to S3
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET }}/${{ secrets.S3_KEY }} \
          --region ${{ secrets.AWS_REGION }}
